services:
  server:
    build:
      context: .
    command: ./mvnw spring-boot:run
    environment:
      DB_URL: db
      DB_PASSWORD: securepassword
      DB_USER: postgres
      DB_DATABASE: postgres
    ports:
      - 8080:8080
    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

