name: ci

on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      -
        name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      -
        name: Run Tests
        run: |
          mvn test
          if [ $? -ne 0 ]; then
            exit 1  
          fi
      -
        name: Generate Docker tag
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      -
        name: Login to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      -
        name: Build and push a docker image
        run: |
          mvn clean package
          if [ $? -ne 0 ]; then
            exit 1  
          fi

          docker build -t ghcr.io/${{ env.REPO }}:latest .
          if [ $? -ne 0 ]; then
            exit 1
          fi

          docker push ghcr.io/${{ env.REPO }}:latest
          if [ $? -ne 0 ]; then
            exit 1
          fi
